title: 发声练习
locale: zh_CN
description: 婴儿般的第一声哭啼
#logo: logo.png
url: https://leetking.github.io/

# markdown: kramdown
kramdown:
  # auto_ids: true
  # auto_id_prefix: ''
  # input: GFM
  # hard_wrap: false
  # toc_level: 1..6
  # math_engine: mathjax
  # syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: text
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 0
      line_format: '%02i'

# liquid:
#     error_mode: warn

# disable plugin jekyll-toc, since Gtihub Page doesn't support
#plugins:
#  - jekyll-toc

# mathjax: true
# coments: true

sass:
  style: compressed
  # sass_dir: _sass

# settings of jekyll-toc plugin
toc:
  min_level: 2
  max_level: 6
  list_class: toc-list
  # item_class: toc-entry
  # item_prefix: toc-

# Front Matter Defaults
defaults:
- scope:
    path: ""    # an empty path here means all files in the project
  values:
    layout: default
- scope:
    path: _posts
    type: posts
  values:
    layout: posts
    toc: true


exclude:
- .gitignore
- .jekyll-cache
- icomoon-selection.json
- todo
- README.md
- LICENSE
