title: 发声练习
locale: zh_CN
description: 如婴儿般的第一声哭啼
#logo: logo.png
url: https://github.com/leetking

encoding: "utf-8"

# markdown: kramdown
# highlighter: rouge

kramdown:
  # auto_ids:     true
  #auto_id_prefix: 'id-'
  # input:        GFM
  # hard_wrap:    false
  # toc_level:    1..6
  math_engine:  mathjax


mathjax: true

coments: true

sass:
  style: compressed
  sass_dir: _sass
